"""create votes table autogenerate

Revision ID: 0d96abb39d88
Revises: ba25bd4e6d15
Create Date: 2024-05-06 13:26:09.062572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0d96abb39d88'
down_revision: Union[str, None] = 'ba25bd4e6d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
        sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='votes_ibfk_1', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='votes_ibfk_2', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('post_id', 'user_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users') 
    # ### end Alembic commands ###
