name: test backend api 

on: [push]

jobs:
  build:
    environment:
      name: testing
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 3306
      DATABASE_PASSWORD: test123123 
      DATABASE_NAME: testDB 
      DATABASE_USERNAME: root
      SECRET_KEY: fb014323d18709100e47fc9b407b21e522676ea533e5dbd80eeaeac56886ef4a
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60 

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test123123
          MYSQL_DATABASE: testDB_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        working-directory: backend
        run: pip install -r requirements.txt
      - name: test with pytest
        run: pytest